"use client"

/**
 * @title VerdictForm
 * @notice Provides a secure interface for reviewers to submit their technical validation of a research publication.
 * @dev This component implements the EIP-712 signing flow to authenticate human reviews before they are 
 * injected into the LangGraph state machine. It handles:
 * 1. Form validation via Zod & React Hook Form.
 * 2. Cryptographic signing of the verdict (Decision + Reason + Metadata).
 * 3. Triggering the server-side LangGraph resumption (resumeReviewersAgent).
 */

import { useNetwork } from "@/app/_hooks/use-network"
import { HumanDecision, HumanDecisionSchema, useOnSignTypeData } from "@/app/_hooks/use-on-sign-typed-data"
import { NetworkT } from "@/app/_schemas/network"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import {
  Field,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLabel,
} from "@/components/ui/field"
import {
  InputGroup,
  InputGroupTextarea
} from "@/components/ui/input-group"
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group"
import { MappedProtocolPublication } from "@/lib/protocol/mappers/protocol-publication-mapper"
import { zodResolver } from "@hookform/resolvers/zod"
import { CheckCircle2Icon, SendIcon, XCircleIcon } from "lucide-react"
import { FC } from "react"
import { Controller, useForm } from "react-hook-form"
import { toast } from "sonner"
import { useConnection } from "wagmi"
import { SignTypedDataVariables } from "wagmi/query"
import * as z from "zod"

/**
 * @notice Parameters required to resume the LangGraph Review Agent.
 * @param threadId Composite ID format: `{publicationId}-{rootCid}`.
 * @param network The blockchain network context (e.g., 'sepolia').
 * @param review The structured review data (Reviewer Address + Verdict).
 * @param signature The EIP-712 signature generated by the reviewer's wallet.
 */
type ResumeReviewersAgentParams = {
  threadId: string
  network: NetworkT
  review: {
    address: `0x${string}`
    verdict: {
      decision: HumanDecision
      reason: string
    }
  }
  signature: `0x${string}`
}

const formSchema = z.object({
  decision: HumanDecisionSchema,
  reason: z.string().min(12, "Justification must be at least 12 characters.")
})

type formSchemaT = z.infer<typeof formSchema>

type Props = {
  /** @dev The mapped publication object containing the ID and CID history. */
  publication: MappedProtocolPublication
}

export const VerdictForm: FC<Props> = (props) => {
  const { publication } = props

  const connection = useConnection()
  const network = useNetwork()

  /** @dev We target the latest CID in the history for the threadId correlation. */
  const rootCid = publication.cids.at(-1) as string
  const publicationId = publication.id.toString()

  const form = useForm<formSchemaT>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      decision: HumanDecisionSchema.enum.fail,
      reason: ""
    },
  })

  /**
   * @notice Executes the LangGraph resumption after a successful EIP-712 signature.
   * @dev This acts as the bridge between the client-side signature and the server-side agentic state.
   */
  // TODO replace with resumeReviewersAgent server action
  const mockResumeReviewersAgent = async (params: ResumeReviewersAgentParams) => {
    console.log("mockResumeReviewersAgent params", params)
  }

  /**
     * @notice Callback triggered once the reviewer signs the typed data in their wallet.
     * @param signature The resulting hex signature.
     * @param variables The variables signed (used to reconstruct the message for the agent).
    */
  const onSuccess = async (signature: `0x${string}`, variables: SignTypedDataVariables, context: unknown) => {
    if (!connection?.address) {
      toast.info("You must be connected to review.")
      return
    }

    /** * @dev threadId must match the split logic used in checkRewiewEip712 on the server.
     */
    await mockResumeReviewersAgent({
      threadId: `${publicationId}-${rootCid}`,
      network,
      review: {
        address: connection.address,
        verdict: {
          decision: variables.message.decision as HumanDecision,
          reason: variables.message.reason as string
        }
      },
      signature
    })
  }

  /**
    * @dev Custom hook abstraction for EIP-712 signing logic.
    * Encapsulates the Domain and Types specific to the BioVerify Protocol.
    */
  const { signTd } = useOnSignTypeData({ publicationId, rootCid, onSuccess })

  /**
   * @notice Primary form submission handler.
   * @dev Validates the connection before triggering the wallet signature request.
   */
  const onSubmit = (data: z.infer<typeof formSchema>) => {
    if (!connection?.address) {
      toast.info("You must be connected to review.")
      return
    }

    signTd({
      reviewer: connection?.address,
      decision: data.decision,
      reason: data.reason
    })
  }

  return (
    <Card className="border-border shadow-md overflow-hidden">
      <CardHeader className="bg-muted/30 border-b pb-4">
        <CardTitle className="text-sm font-bold uppercase tracking-wider text-muted-foreground">
          Submit Verdict
        </CardTitle>
      </CardHeader>
      <CardContent className="p-6 space-y-6">
        <form id="form-review" onSubmit={form.handleSubmit(onSubmit)}>
          <FieldGroup>
            <Controller
              name="decision"
              control={form.control}
              render={({ field, fieldState }) => (
                <Field data-invalid={fieldState.invalid} className="space-y-3">
                  <FieldLabel htmlFor="decision" className="text-[10px] font-bold uppercase text-muted-foreground/80">
                    Decision
                  </FieldLabel>
                  <ToggleGroup
                    type="single"
                    className="grid grid-cols-2 gap-4"
                    onValueChange={field.onChange}
                  >
                    <ToggleGroupItem
                      value={HumanDecisionSchema.enum.pass}
                      className="h-20 flex flex-col gap-2 border-2 data-[state=on]:border-primary data-[state=on]:bg-primary/5"
                    >
                      <CheckCircle2Icon className="h-5 w-5 text-green-500" />
                      <span className="text-xs font-bold uppercase">Valid</span>
                    </ToggleGroupItem>
                    <ToggleGroupItem
                      value={HumanDecisionSchema.enum.fail}
                      className="h-20 flex flex-col gap-2 border-2 data-[state=on]:border-destructive data-[state=on]:bg-destructive/5"
                    >
                      <XCircleIcon className="h-5 w-5 text-destructive" />
                      <span className="text-xs font-bold uppercase">Invalid</span>
                    </ToggleGroupItem>
                  </ToggleGroup>
                </Field>
              )}
            />

            <Controller
              name="reason"
              control={form.control}
              render={({ field, fieldState }) => (
                <Field data-invalid={fieldState.invalid} className="space-y-3">
                  <FieldLabel htmlFor="reason" className="text-[10px] font-bold uppercase text-muted-foreground/80">
                    Reason
                  </FieldLabel>
                  <InputGroup>
                    <InputGroupTextarea
                      {...field}
                      id="reason"
                      placeholder="Provide technical feedback for the author..."
                      rows={6}
                      className="min-h-30 resize-none bg-muted/20"
                      aria-invalid={fieldState.invalid}
                    />
                  </InputGroup>
                  <FieldDescription>
                    Include steps to reproduce, expected behavior, and what
                    actually happened.
                  </FieldDescription>
                  {fieldState.invalid && (
                    <FieldError errors={[fieldState.error]} />
                  )}
                </Field>
              )}
            />
          </FieldGroup>
        </form>
      </CardContent>

      <CardFooter>
        <Field orientation="horizontal">
          <Button type="button" variant="outline" onClick={() => form.reset()}>
            Reset
          </Button>
          <Button type="submit" form="form-review"
            className="w-full font-bold h-12">
            <SendIcon className="mr-2 h-4 w-4" />
            Broadcast Review
          </Button>
        </Field>
      </CardFooter>
    </Card>
  )
}