import { Product } from "./_components/publications-table/columns"
import { FacetedFilterTable } from "./_components/publications-table/faceted-filter-table"
import { SubmitPublicationForm } from "./_components/submit-publication-form/submit-publication-form"

const products: Product[] = [
	{
		id: "p1",
		name: "iPhone 15 Pro Max",
		category: "Smartphones",
		brand: "Apple",
		price: 1299.99,
		stock: 45,
		rating: 4.8,
		inStock: true,
		releaseDate: new Date("2023-09-22"),
	},
	{
		id: "p2",
		name: "MacBook Pro M3",
		category: "Laptops",
		brand: "Apple",
		price: 1999.99,
		stock: 22,
		rating: 4.9,
		inStock: true,
		releaseDate: new Date("2023-11-10"),
	},
	{
		id: "p3",
		name: "Galaxy S24 Ultra",
		category: "Smartphones",
		brand: "Samsung",
		price: 1199.99,
		stock: 30,
		rating: 4.7,
		inStock: true,
		releaseDate: new Date("2024-01-26"),
	},
	{
		id: "p4",
		name: "PlayStation 5 Slim",
		category: "Gaming",
		brand: "Sony",
		price: 499.99,
		stock: 15,
		rating: 4.6,
		inStock: true,
		releaseDate: new Date("2023-11-15"),
	},
	{
		id: "p5",
		name: "AirPods Pro 2nd Gen",
		category: "Audio",
		brand: "Apple",
		price: 249.99,
		stock: 50,
		rating: 4.5,
		inStock: true,
		releaseDate: new Date("2022-09-23"),
	},
	{
		id: "p6",
		name: "Dell XPS 15",
		category: "Laptops",
		brand: "Dell",
		price: 1799.99,
		stock: 12,
		rating: 4.4,
		inStock: true,
		releaseDate: new Date("2023-07-14"),
	},
	{
		id: "p7",
		name: "Sony WH-1000XM5",
		category: "Audio",
		brand: "Sony",
		price: 399.99,
		stock: 18,
		rating: 4.8,
		inStock: true,
		releaseDate: new Date("2022-05-12"),
	},
	{
		id: "p8",
		name: "Nintendo Switch OLED",
		category: "Gaming",
		brand: "Nintendo",
		price: 349.99,
		stock: 25,
		rating: 4.7,
		inStock: true,
		releaseDate: new Date("2021-10-08"),
	},
	{
		id: "p9",
		name: "Google Pixel 8 Pro",
		category: "Smartphones",
		brand: "Google",
		price: 999.99,
		stock: 20,
		rating: 4.6,
		inStock: true,
		releaseDate: new Date("2023-10-12"),
	},
	{
		id: "p10",
		name: "Bose QuietComfort Ultra",
		category: "Audio",
		brand: "Bose",
		price: 429.99,
		stock: 10,
		rating: 4.5,
		inStock: true,
		releaseDate: new Date("2023-09-28"),
	},
	{
		id: "p11",
		name: "Meta Quest 3",
		category: "VR",
		brand: "Meta",
		price: 499.99,
		stock: 8,
		rating: 4.3,
		inStock: true,
		releaseDate: new Date("2023-10-10"),
	},
	{
		id: "p12",
		name: "Apple Watch Series 9",
		category: "Wearables",
		brand: "Apple",
		price: 399.99,
		stock: 35,
		rating: 4.4,
		inStock: true,
		releaseDate: new Date("2023-09-20"),
	},
	{
		id: "p13",
		name: "Samsung Odyssey G9",
		category: "Monitors",
		brand: "Samsung",
		price: 1499.99,
		stock: 5,
		rating: 4.7,
		inStock: true,
		releaseDate: new Date("2023-07-13"),
	},
	{
		id: "p14",
		name: "Logitech MX Master 3S",
		category: "Accessories",
		brand: "Logitech",
		price: 99.99,
		stock: 40,
		rating: 4.6,
		inStock: true,
		releaseDate: new Date("2022-06-07"),
	},
	{
		id: "p15",
		name: "DJI Mini 4 Pro",
		category: "Drones",
		brand: "DJI",
		price: 759.99,
		stock: 7,
		rating: 4.8,
		inStock: true,
		releaseDate: new Date("2023-09-25"),
	},
]

export default function Home() {
	return (
		<div className="flex min-h-screen items-center justify-center bg-zinc-50 font-sans dark:bg-black">
			<main className="flex min-h-screen w-full max-w-4xl flex-col items-center justify-between py-32 px-16 bg-white dark:bg-black sm:items-start">

				<FacetedFilterTable data={products} />
				<SubmitPublicationForm />

			</main>
		</div>
	)
}
