#!/usr/bin/env node

/**
 * Reads Foundry build artifacts (out/ and broadcast/) and regenerates
 * packages/utils/protocol/bioverfiy-contract-config.ts with the latest
 * ABI and deployed addresses. Safe to run after a single-network deploy —
 * missing broadcast files fall back to whatever address is already in the
 * existing config.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const CONTRACTS_ROOT = resolve(__dirname, "..")
const CONFIG_PATH = resolve(
  CONTRACTS_ROOT,
  "../../packages/utils/protocol/bioverfiy-contract-config.ts",
)

const NETWORKS = {
  base_sepolia: { chainId: "84532", configVar: "bioVerifyConfigBaseSepolia" },
  eth_sepolia: {
    chainId: "11155111",
    configVar: "bioVerifyConfigEthSepolia",
  },
}

// ---------------------------------------------------------------------------
// 1. Read ABI from compiled output
// ---------------------------------------------------------------------------
const abiPath = resolve(
  CONTRACTS_ROOT,
  "out/BioVerifyV3.sol/BioVerifyV3.json",
)
if (!existsSync(abiPath)) {
  console.error(
    `[post-deploy] Compiled artifact not found at ${abiPath}\n` +
    "Run forge compile (or a deploy) first.",
  )
  process.exit(1)
}
const { abi } = JSON.parse(readFileSync(abiPath, "utf-8"))

// ---------------------------------------------------------------------------
// 2. Resolve addresses — prefer broadcast, fall back to existing config
// ---------------------------------------------------------------------------
function addressFromBroadcast(chainId) {
  const broadcastPath = resolve(
    CONTRACTS_ROOT,
    `broadcast/BioVerifyV3.s.sol/${chainId}/run-latest.json`,
  )
  if (!existsSync(broadcastPath)) return null
  const { transactions } = JSON.parse(readFileSync(broadcastPath, "utf-8"))
  const createTx = transactions.find(
    (tx) =>
      tx.transactionType === "CREATE" &&
      tx.contractName === "BioVerifyV3",
  )
  return createTx?.contractAddress ?? null
}

function addressFromExistingConfig(varName) {
  if (!existsSync(CONFIG_PATH)) return null
  const src = readFileSync(CONFIG_PATH, "utf-8")
  const re = new RegExp(
    `const\\s+${varName}[\\s\\S]*?address:\\s*"(0x[0-9a-fA-F]+)"`,
  )
  return src.match(re)?.[1] ?? null
}

const addresses = {}
for (const [network, { chainId, configVar }] of Object.entries(NETWORKS)) {
  const addr =
    addressFromBroadcast(chainId) ?? addressFromExistingConfig(configVar)
  if (!addr) {
    console.error(
      `[post-deploy] No address found for ${network} (chainId ${chainId}).\n` +
      "Deploy to this network at least once, or ensure the existing config has an address.",
    )
    process.exit(1)
  }
  addresses[network] = addr
}

// ---------------------------------------------------------------------------
// 3. Generate the TypeScript config
// ---------------------------------------------------------------------------
function networkConfig(varName, address) {
  return [
    `const ${varName}: ContractConfig = {`,
    `\taddress: "${address}",`,
    "\tabi: bioVerifyAbi as Abi,",
    "}",
  ].join("\n")
}

const sections = [
  "// THIS FILE IS AUTO-GENERATED by apps/contracts/scripts/post-deploy.mjs",
  "// Do not edit manually. Run `pnpm contract:sync-config` to regenerate.",
  "",
  'import { NetworkSchema, type NetworkT } from "@packages/schema"',
  'import type { Abi } from "viem"',
  "",
  "export type ContractConfig = {",
  "\taddress: `0x${string}`",
  "\tabi: Abi",
  "}",
  "",
  `export const bioVerifyAbi = ${JSON.stringify(abi, null, "\t")}`,
  "",
  networkConfig("bioVerifyConfigBaseSepolia", addresses.base_sepolia),
  "",
  networkConfig("bioVerifyConfigEthSepolia", addresses.eth_sepolia),
  "",
  "export const BioVerifyContractConfig: Record<NetworkT, ContractConfig> = {",
  "\t[NetworkSchema.enum.base_sepolia]: bioVerifyConfigBaseSepolia,",
  "\t[NetworkSchema.enum.eth_sepolia]: bioVerifyConfigEthSepolia,",
  "}",
  "",
]

writeFileSync(CONFIG_PATH, sections.join("\n"), "utf-8")

console.log("[post-deploy] Updated contract config:")
console.log(`  Base Sepolia  → ${addresses.base_sepolia}`)
console.log(`  Eth Sepolia   → ${addresses.eth_sepolia}`)
console.log(`  ABI entries   → ${abi.length}`)
console.log(`  Written to    → ${CONFIG_PATH}`)
